### ISSUE TITLE
Your username isn't linked in your commits

### ISSUE THREAD

**Issue by AnthonyMastrean** [digitaldrummerj-chocolatey/ChocolateyPackages#6]
Have you configured your git client to set your username and email address? Your username in commits should be a link.

![image](https://cloud.githubusercontent.com/assets/217842/6607297/114eba3c-c814-11e4-9ae4-d0ee66180eaf.png)

GitHub has a guide for this (I assume you're on Windows, because Chocolatey).

https://help.github.com/articles/setting-your-username-in-git/

**Comment by digitaldrummerj** [comment]
Should be fixed now.

Thx
