### ISSUE TITLE
JAVA_HOME not set in JDK7 v7.0.79 package

### ISSUE THREAD

**Issue by itlackey** [digitaldrummerj-chocolatey/ChocolateyPackages#9]
It appears that the $java_home variable does not get set after the jdk is installed and before it is used to set the environment variable on line 42. Looking through the code and previous versions, it looks like a call to get-java-home has fallen into the abyss at some point. I believe it should be called around line 41 in chocolateyInstall.ps1

**Comment by digitaldrummerj** [comment]
It is already being set on line 22.

**Comment by digitaldrummerj** [comment]
new version released that fixed this.

**Comment by itlackey** [comment]
thank you!
